<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="latest"
     targetNamespace="http://xmlns.oracle.com/chitchat/rest-server/latest"
     xmlns:tns="http://xmlns.oracle.com/chitchat/rest-server/latest"
     xmlns:inp1="http://anteoconsulting.com/chitchat_POST_request"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="latest">
        <plnk:role name="latestProvider" portType="tns:latest_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://anteoconsulting.com/chitchat_POST_request" schemaLocation="../Schemas/tweet_schema.xsd"/>
        </xsd:schema>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.oracle.com/chitchat/rest-server/latest"
             elementFormDefault="qualified">
            <element name="latest_params">
                <complexType>
                    <sequence>
                        <element name="author" type="string"/>
                    </sequence>
                </complexType>
            </element>
        </schema>
    </wsdl:types>
    <wsdl:message name="latest_inputMessage">
        <wsdl:part name="request" element="tns:latest_params"/>
    </wsdl:message>
    <wsdl:message name="latest_outputMessage">
        <wsdl:part name="reply" element="inp1:tweet"/>
    </wsdl:message>
    <wsdl:portType name="latest_ptt">
        <wsdl:operation name="latest">
            <wsdl:input message="tns:latest_inputMessage"/>
            <wsdl:output message="tns:latest_outputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
